"""
ResSmith: Reservoir engineering library.

A comprehensive reservoir engineering toolkit with strict 4-layer architecture
for production analysis, decline curve analysis, forecasting, and economic evaluation.
"""

__version__ = "0.2.2"

# Public API: Workflows
# Public API: Core objects
from ressmith.objects import (
    CumSeries,
    DeclineSpec,
    EconResult,
    EconSpec,
    ForecastResult,
    ForecastSpec,
    ProductionSeries,
    RateSeries,
    WellMeta,
)

# Public API: Base types
from ressmith.primitives.base import BaseDeclineModel, BaseEconModel
from ressmith.workflows import (
    aggregate_portfolio_forecast,
    analyze_blasingame,
    analyze_choke_performance,
    analyze_dn_type_curve,
    analyze_fmb,
    analyze_fracture_network,
    analyze_interference_matrix,
    analyze_interference_with_production_history,
    analyze_multi_well_interaction,
    analyze_parameter_sensitivity,
    analyze_portfolio,
    analyze_waterflood,
    analyze_well_coning,
    analyze_well_pattern,
    apply_hysteresis_workflow,
    calculate_history_match_objective,
    calculate_mobility_ratio_workflow,
    calculate_pseudopressure_workflow,
    calculate_sensitivity_coefficients,
    compare_artificial_lift_methods,
    compare_models,
    compare_simulation_to_forecast,
    create_well_pointset,
    detect_outliers,
    ensemble_forecast,
    estimate_eur,
    evaluate_economics,
    evaluate_scenarios,
    export_for_simulator,
    export_simulator_input,
    fit_forecast,
    fit_segmented_forecast,
    forecast_many,
    forecast_with_yields,
    forecast_wor_gor_with_coning,
    full_run,
    generate_all_diagnostic_plots,
    generate_capillary_pressure_curve,
    generate_diagnostic_plot_data,
    generate_oil_water_relative_permeability,
    generate_relative_permeability_curves,
    generate_three_phase_relative_permeability,
    history_match_material_balance,
    identify_critical_parameters,
    import_simulation_results,
    import_simulator_output,
    map_portfolio_spatially,
    match_type_curve_workflow,
    normalize_for_rta_analysis,
    normalize_production_with_pressure,
    optimize_choke_size,
    optimize_esp_system,
    optimize_field_spacing,
    optimize_gas_lift_system,
    optimize_multi_stage_fracture,
    optimize_rod_pump_system,
    plot_boundary_dominated_flow,
    plot_diagnostic_with_flow_regime_identification,
    plot_forecast,
    plot_linear_flow_diagnostic,
    plot_log_log_diagnostic,
    plot_sqrt_time_diagnostic,
    predict_waterflood_performance,
    probabilistic_forecast,
    rank_wells,
    recommend_spacing,
    recommend_spacing_from_eur,
    run_parameter_sensitivity_analysis,
    scenario_summary,
    spatial_analysis,
    validate_and_analyze_well_test,
    validate_well_test_data,
    validate_well_test_results,
    walk_forward_backtest,
)

__all__ = [
    # Workflows - Core
    "fit_forecast",
    "fit_segmented_forecast",
    "forecast_many",
    "forecast_with_yields",
    "ensemble_forecast",
    "probabilistic_forecast",
    "evaluate_economics",
    "evaluate_scenarios",
    "scenario_summary",
    "walk_forward_backtest",
    "compare_models",
    "estimate_eur",
    "full_run",
    "plot_forecast",
    "detect_outliers",
    "spatial_analysis",
    "create_well_pointset",
    "map_portfolio_spatially",
    "analyze_portfolio",
    "aggregate_portfolio_forecast",
    "rank_wells",
    # Multi-well interaction
    "analyze_multi_well_interaction",
    "optimize_field_spacing",
    "analyze_well_pattern",
    "analyze_interference_matrix",
    "analyze_interference_with_production_history",
    "recommend_spacing",
    "recommend_spacing_from_eur",
    # Coning analysis
    "analyze_well_coning",
    "forecast_wor_gor_with_coning",
    # EOR workflows
    "analyze_waterflood",
    "calculate_mobility_ratio_workflow",
    "predict_waterflood_performance",
    # Pressure normalization
    "normalize_production_with_pressure",
    "normalize_for_rta_analysis",
    "calculate_pseudopressure_workflow",
    # Relative permeability
    "generate_relative_permeability_curves",
    "generate_oil_water_relative_permeability",
    "generate_three_phase_relative_permeability",
    "generate_capillary_pressure_curve",
    "apply_hysteresis_workflow",
    # Choke optimization
    "optimize_choke_size",
    "analyze_choke_performance",
    # Artificial lift optimization
    "optimize_esp_system",
    "optimize_gas_lift_system",
    "optimize_rod_pump_system",
    "compare_artificial_lift_methods",
    # Type curves & RTA
    "match_type_curve_workflow",
    "generate_diagnostic_plot_data",
    "generate_all_diagnostic_plots",
    "plot_diagnostic_with_flow_regime_identification",
    "plot_log_log_diagnostic",
    "plot_sqrt_time_diagnostic",
    "plot_linear_flow_diagnostic",
    "plot_boundary_dominated_flow",
    "analyze_blasingame",
    "analyze_dn_type_curve",
    "analyze_fmb",
    "analyze_fracture_network",
    "optimize_multi_stage_fracture",
    # History Matching & Simulator Integration
    "history_match_material_balance",
    "calculate_history_match_objective",
    "run_parameter_sensitivity_analysis",
    "analyze_parameter_sensitivity",
    "calculate_sensitivity_coefficients",
    "identify_critical_parameters",
    "export_for_simulator",
    "export_simulator_input",
    "import_simulation_results",
    "import_simulator_output",
    "compare_simulation_to_forecast",
    # Well Test Validation
    "validate_well_test_data",
    "validate_well_test_results",
    "validate_and_analyze_well_test",
    # Base types
    "BaseDeclineModel",
    "BaseEconModel",
    # Core objects
    "WellMeta",
    "ProductionSeries",
    "RateSeries",
    "CumSeries",
    "DeclineSpec",
    "ForecastSpec",
    "EconSpec",
    "ForecastResult",
    "EconResult",
    # DCA API (decline-curve / PetroSmith compatibility)
    "dca",
]

# DCA API - imported after workflows to avoid circular imports
import ressmith.dca as dca
